use_frameworks!

platform :ios, '9.0'

target 'ORCropImageController_Example' do
  pod 'ORCropImageController', :path => '../'

  target 'ORCropImageController_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
